### ISSUE TITLE
训练设置问题咨询

### ISSUE THREAD

**Issue by progressforever** [kakaxi314/BP-Net#1]
请问您在kitti榜单上的效果是否有在nyu数据集上预训练呢？还是只在kitti数据集上训练得到的结果？
谢谢~

**Comment by kakaxi314** [comment]
Our *BP_KITTI* model is trained with the train set of KITTI data from scratch.

**Comment by progressforever** [comment]
> Our _BP_KITTI_ model is trained with the train set of KITTI data from scratch.
