### ISSUE TITLE
Can't find datas/kitti/raw

### ISSUE THREAD

**Issue by KeiichiKasai** [kakaxi314/BP-Net#13]
Hello! There's a small problem: where can I find the "data/kitti/raw"?
![~TXB3N NY_K WF8CKML)59E](https://github.com/kakaxi314/BP-Net/assets/114374670/edda4f25-899d-4da2-8cef-4a6b9775689a)

https://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_completion
Only provided other files without the ''raw''

**Comment by KeiichiKasai** [comment]
I downloaded the raw archive of the official website.,But I didn't _calib_cam_to_cam.txt_ this file.,Can you tell me how to get this file or tell me the contents of this file？I'd appreciate it if you could help

**Comment by csdnidol** [comment]
> I downloaded the raw archive of the official website.,But I didn't _calib_cam_to_cam.txt_ this file.,Can you tell me how to get this file or tell me the contents of this file？I'd appreciate it if you could help我下载了官方网站的原始档案。但是我没有calib_cam_to_cam.txt这个文件。你能告诉我如何得到这个文件或者告诉我这个文件的内容吗？如果你能帮忙，我会很感激的

raw在另一部分，https://www.cvlibs.net/datasets/kitti/raw_data.php
